services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - PUBLIC_WEBSOCKET_BASE_URL=${PUBLIC_WEBSOCKET_BASE_URL:-}
    ports:
      - '3000:3000'
    env_file:
      - path: apps/web/.env
        required: false
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - path: apps/backend/.env
        required: false
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
